import Head from "next/head";
import Banner from "@components/header";
import ContactUs from "@components/contact-us";
import Articles from "@components/articles";
import axios from "axios";
import toast from "react-hot-toast";

export default function Home() {
  const postNewsletter = async (data: any) => {
    await axios
      .post("https://5eed24da4cbc340016330f0d.mockapi.io/api/newsletter", data)
      .then(function (response) {
        toast.success("Enviado correctamente");
        return response.data;
      })
      .catch(function (err) {
        toast.error("Hubo un error en el envio de datos");
        console.error(err);
      });
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full bg-grey-50">

        <Banner />
        <Articles />
        <ContactUs onSubmit={postNewsletter} />
      </main>
    </div>
  );
}
